#############################################################################
# Generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#  Jan 06, 2022 12:01:26 AM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #7EB0F2 -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowFrame 
    wm focusmodel $top passive
    wm geometry $top 606x586+349+124
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 881
    wm minsize $top 120 10
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "solver"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "solver" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #3084F2 -compound left -disabledforeground #a3a3a3 \
        -font {-family Calibri -size 18 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Solve 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "solver" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #3084F2 -compound left -disabledforeground #a3a3a3 \
        -font {-family Calibri -size 18 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Reset 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa49 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text {Equation 1 :} \
        -compound left 
    vTcl:DefineAlias "$top.tLa49" "Label_Equation1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn54 \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tEn54" "Entry1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn55 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn55" "Entry2" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn56 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn56" "Entry3" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn57 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn57" "Entry4" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa58 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { X +} -compound left 
    vTcl:DefineAlias "$top.tLa58" "TLabelX1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn61 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn61" "Entry5" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn63 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn63" "Entry6" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn65 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn65" "Entry7" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn67 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn67" "Entry8" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn68 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn68" "Entry9" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn70 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn70" "Entry10" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn72 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn72" "Entry11" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn74 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn74" "Entry12" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn78 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn78" "Entry15" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn79 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn79" "Entry14" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn81 \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tEn81" "Entry13" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa82 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 14 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text {Results :} -compound left 
    vTcl:DefineAlias "$top.tLa82" "TLabel_results" vTcl:WidgetProc "solver" 1
    label $top.lab46 \
        -anchor w -background #0455BF -disabledforeground #a3a3a3 \
        -font {-family Calibri -size 22 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -padx 10 \
        -text {Solving a 3X3 system of linear equations by ZMB} 
    vTcl:DefineAlias "$top.lab46" "App_title" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa47 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text {Equation 2 :} \
        -compound left 
    vTcl:DefineAlias "$top.tLa47" "Label_Equation2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa48 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text {Equation 3 :} \
        -compound left 
    vTcl:DefineAlias "$top.tLa48" "Label_Equation3" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa50 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { X +} -compound left 
    vTcl:DefineAlias "$top.tLa50" "TLabelX2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa51 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Y +} -compound left 
    vTcl:DefineAlias "$top.tLa51" "TLabelY1" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa52 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Z  =} -compound left 
    vTcl:DefineAlias "$top.tLa52" "TLabelZ1" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa53 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { X +} -compound left 
    vTcl:DefineAlias "$top.tLa53" "TLabelX3" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa54 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { X =} -compound left 
    vTcl:DefineAlias "$top.tLa54" "TLabelX4" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa55 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Y +} -compound left 
    vTcl:DefineAlias "$top.tLa55" "TLabelY2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa56 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Y +} -compound left 
    vTcl:DefineAlias "$top.tLa56" "TLabelY3" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa57 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Y =} -compound left 
    vTcl:DefineAlias "$top.tLa57" "TLabelY4" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa59 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Z  =} -compound left 
    vTcl:DefineAlias "$top.tLa59" "TLabelZ2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa60 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Z  =} -compound left 
    vTcl:DefineAlias "$top.tLa60" "TLabelZ3" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa61 \
        -background #7EB0F2 -foreground $vTcl(actual_gui_fg) \
        -font {-family Calibri -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text { Z =} -compound left 
    vTcl:DefineAlias "$top.tLa61" "TLabelZ4" vTcl:WidgetProc "solver" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.7 -width 280 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.512 -y 0 -rely 0.697 -width 259 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa49 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.204 -width 0 -relwidth 0.143 \
        -height 0 -relheight 0.041 -anchor nw -bordermode ignore 
    place $top.tEn54 \
        -in $top -x 0 -relx 0.064 -y 0 -rely 0.255 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn55 \
        -in $top -x 0 -relx 0.297 -y 0 -rely 0.255 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn56 \
        -in $top -x 0 -relx 0.528 -y 0 -rely 0.255 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn57 \
        -in $top -x 0 -relx 0.776 -y 0 -rely 0.255 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tLa58 \
        -in $top -x 0 -relx 0.231 -y 0 -rely 0.255 -width 0 -relwidth 0.061 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tEn61 \
        -in $top -x 0 -relx 0.061 -y 0 -rely 0.408 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn63 \
        -in $top -x 0 -relx 0.297 -y 0 -rely 0.408 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn65 \
        -in $top -x 0 -relx 0.528 -y 0 -rely 0.408 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn67 \
        -in $top -x 0 -relx 0.776 -y 0 -rely 0.408 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn68 \
        -in $top -x 0 -relx 0.061 -y 0 -rely 0.561 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn70 \
        -in $top -x 0 -relx 0.297 -y 0 -rely 0.561 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn72 \
        -in $top -x 0 -relx 0.528 -y 0 -rely 0.561 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn74 \
        -in $top -x 0 -relx 0.776 -y 0 -rely 0.561 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn78 \
        -in $top -x 0 -relx 0.759 -y 0 -rely 0.853 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn79 \
        -in $top -x 0 -relx 0.528 -y 0 -rely 0.853 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tEn81 \
        -in $top -x 0 -relx 0.297 -y 0 -rely 0.853 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.tLa82 \
        -in $top -x 0 -relx 0.066 -y 0 -rely 0.836 -width 0 -relwidth 0.137 \
        -height 0 -relheight 0.089 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.005 -height 0 \
        -relheight 0.172 -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.34 -width 0 -relwidth 0.143 \
        -height 0 -relheight 0.041 -anchor nw -bordermode ignore 
    place $top.tLa48 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.493 -width 0 -relwidth 0.143 \
        -height 0 -relheight 0.041 -anchor nw -bordermode ignore 
    place $top.tLa50 \
        -in $top -x 0 -relx 0.231 -y 0 -rely 0.408 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 0 -relx 0.462 -y 0 -rely 0.255 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.255 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 0 -relx 0.231 -y 0 -rely 0.563 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa54 \
        -in $top -x 0 -relx 0.231 -y 0 -rely 0.853 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa55 \
        -in $top -x 0 -relx 0.462 -y 0 -rely 0.408 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa56 \
        -in $top -x 0 -relx 0.462 -y 0 -rely 0.563 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa57 \
        -in $top -x 0 -relx 0.462 -y 0 -rely 0.853 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa59 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.408 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa60 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.561 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa61 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.853 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

