#############################################################################
# Generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#  Jan 05, 2022 05:08:27 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #80ffff -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowFrame 
    wm focusmodel $top passive
    wm geometry $top 651x490+349+124
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "solver"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "solver" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Solve 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "solver" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Clear 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa49 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Equation 1} -compound left 
    vTcl:DefineAlias "$top.tLa49" "TLabel1" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Equation 2} -compound left 
    vTcl:DefineAlias "$top.tLa51" "TLabel2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Equation 3} -compound left 
    vTcl:DefineAlias "$top.tLa52" "TLabel3" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn54 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn54" "Entry1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn55 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn55" "Entry2" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn56 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn56" "Entry3" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn57 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn57" "Entry4" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa58 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { X +} \
        -compound left 
    vTcl:DefineAlias "$top.tLa58" "TLabel4_1" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa59 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { Y +} \
        -compound left 
    vTcl:DefineAlias "$top.tLa59" "TLabel4_2" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa60 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text { Z  =} -compound left 
    vTcl:DefineAlias "$top.tLa60" "TLabel4_3" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn61 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn61" "Entry5" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa62 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { X +} \
        -compound left 
    vTcl:DefineAlias "$top.tLa62" "TLabel4_1_1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn63 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn63" "Entry6" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa64 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { Y +} \
        -compound left 
    vTcl:DefineAlias "$top.tLa64" "TLabel4_2_1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn65 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn65" "Entry7" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa66 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text { Z  =} -compound left 
    vTcl:DefineAlias "$top.tLa66" "TLabel4_3_1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn67 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn67" "Entry8" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn68 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn68" "Entry9" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa69 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { X +} \
        -compound left 
    vTcl:DefineAlias "$top.tLa69" "TLabel4_1_1_1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn70 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn70" "Entry10" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa71 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { Y +} \
        -compound left 
    vTcl:DefineAlias "$top.tLa71" "TLabel4_2_1_1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn72 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn72" "Entry11" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa73 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text { Z  =} -compound left 
    vTcl:DefineAlias "$top.tLa73" "TLabel4_3_1_1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn74 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn74" "Entry12" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa75 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { X =} \
        -compound left 
    vTcl:DefineAlias "$top.tLa75" "TLabel4_1_1_1_1" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa76 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text { Y =} \
        -compound left 
    vTcl:DefineAlias "$top.tLa76" "TLabel4_2_1_1_1" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa77 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text { Z  =} -compound left 
    vTcl:DefineAlias "$top.tLa77" "TLabel4_3_1_1_1" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn78 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn78" "Entry15" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn79 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn79" "Entry14" vTcl:WidgetProc "solver" 1
    ttk::entry $top.tEn81 \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tEn81" "Entry13" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa82 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text Results -compound left 
    vTcl:DefineAlias "$top.tLa82" "TLabel4" vTcl:WidgetProc "solver" 1
    ttk::label $top.tLa46 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text ZMB \
        -compound left 
    vTcl:DefineAlias "$top.tLa46" "TLabel5" vTcl:WidgetProc "solver" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 0 -relx 0.077 -y 0 -rely 0.612 -width 67 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.215 -y 0 -rely 0.612 -width 67 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa49 \
        -in $top -x 0 -relx 0.078 -y 0 -rely 0.078 -width 0 -relwidth 0.097 \
        -height 0 -relheight 0.041 -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 0 -relx 0.078 -y 0 -rely 0.249 -width 0 -relwidth 0.101 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 0 -relx 0.077 -y 0 -rely 0.429 -width 0 -relwidth 0.101 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.tEn54 \
        -in $top -x 0 -relx 0.108 -y 0 -rely 0.151 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tEn55 \
        -in $top -x 0 -relx 0.292 -y 0 -rely 0.151 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tEn56 \
        -in $top -x 0 -relx 0.476 -y 0 -rely 0.151 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tEn57 \
        -in $top -x 0 -relx 0.661 -y 0 -rely 0.151 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tLa58 \
        -in $top -x 0 -relx 0.23 -y 0 -rely 0.15 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa59 \
        -in $top -x 0 -relx 0.415 -y 0 -rely 0.15 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tLa60 \
        -in $top -x 0 -relx 0.599 -y 0 -rely 0.15 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tEn61 \
        -in $top -x 0 -relx 0.092 -y 0 -rely 0.327 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tLa62 \
        -in $top -x 0 -relx 0.23 -y 0 -rely 0.327 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tEn63 \
        -in $top -x 0 -relx 0.292 -y 0 -rely 0.327 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.tLa64 \
        -in $top -x 0 -relx 0.415 -y 0 -rely 0.327 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tEn65 \
        -in $top -x 0 -relx 0.476 -y 0 -rely 0.327 -width 73 -relwidth 0 \
        -height 29 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa66 \
        -in $top -x 0 -relx 0.599 -y 0 -rely 0.327 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tEn67 \
        -in $top -x 0 -relx 0.661 -y 0 -rely 0.327 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tEn68 \
        -in $top -x 0 -relx 0.092 -y 0 -rely 0.49 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tLa69 \
        -in $top -x 0 -relx 0.23 -y 0 -rely 0.49 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tEn70 \
        -in $top -x 0 -relx 0.292 -y 0 -rely 0.49 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tLa71 \
        -in $top -x 0 -relx 0.415 -y 0 -rely 0.49 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tEn72 \
        -in $top -x 0 -relx 0.476 -y 0 -rely 0.49 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.tLa73 \
        -in $top -x 0 -relx 0.599 -y 0 -rely 0.49 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tEn74 \
        -in $top -x 0 -relx 0.661 -y 0 -rely 0.49 -width 0 -relwidth 0.112 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tLa75 \
        -in $top -x 0 -relx 0.23 -y 0 -rely 0.755 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tLa76 \
        -in $top -x 0 -relx 0.415 -y 0 -rely 0.755 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tLa77 \
        -in $top -x 0 -relx 0.599 -y 0 -rely 0.755 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tEn78 \
        -in $top -x 0 -relx 0.661 -y 0 -rely 0.755 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.tEn79 \
        -in $top -x 0 -relx 0.476 -y 0 -rely 0.755 -width 0 -relwidth 0.114 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.tEn81 \
        -in $top -x 0 -relx 0.292 -y 0 -rely 0.755 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.tLa82 \
        -in $top -x 0 -relx 0.092 -y 0 -rely 0.755 -width 0 -relwidth 0.074 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tLa46 \
        -in $top -x 0 -relx 0.86 -y 0 -rely 0.918 -width 0 -relwidth 0.054 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

