#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#    Jan 06, 2022 12:01:53 AM CET  platform: Windows NT

import sys
import numpy as np
import tkinter.messagebox as fmsgbox
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import Linear_Solver_System_support

class solver:
    def doRefresh(self):
         self.Entry1.delete(0, END)
         self.Entry2.delete(0, END)
         self.Entry3.delete(0, END)
         self.Entry4.delete(0, END)
         self.Entry5.delete(0, END)
         self.Entry6.delete(0, END)
         self.Entry7.delete(0, END)
         self.Entry8.delete(0, END)
         self.Entry9.delete(0, END)
         self.Entry10.delete(0, END)
         self.Entry11.delete(0, END)
         self.Entry12.delete(0, END)
         self.Entry13.delete(0, END)
         self.Entry14.delete(0, END)
         self.Entry15.delete(0, END)
         return
             
    def solveMatrix(self):
        condition1 = ((self.Entry1.get() is "") or (self.Entry2.get() is "") or (self.Entry3.get() is "") or
			          (self.Entry4.get() is "") or (self.Entry5.get() is "") or (self.Entry6.get() is "") or
			          (self.Entry7.get() is "") or (self.Entry8.get() is "") or (self.Entry9.get() is "") or
			          (self.Entry10.get() is "") or (self.Entry11.get() is "") or (self.Entry12.get() is ""))
        if (condition1 is True):
                fmsgbox.showinfo("Solver", "Empty user input. Please check!")
                return
        matrix1 = np.array([[float(self.Entry1.get()),float(self.Entry2.get()),float(self.Entry3.get())],
                    [float(self.Entry5.get()),float(self.Entry6.get()),float(self.Entry7.get())],
                    [float(self.Entry9.get()),float(self.Entry10.get()),float(self.Entry11.get())]])
        matrix2 = np.linalg.inv(matrix1)
        matrix3 = np.array([float(self.Entry4.get()), float(self.Entry8.get()), float(self.Entry12.get())])
        results = np.round(matrix2.dot(matrix3),decimals=10)
        self.Entry13.insert(0,results[0])
        self.Entry14.insert(0,results[1])
        self.Entry15.insert(0,results[2])
        return
    
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("606x586+349+124")
        top.minsize(120, 10)
        top.maxsize(1444, 881)
        top.resizable(1,  1)
        top.title("solver")
        top.configure(background="#7EB0F2")

        self.top = top

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.033, rely=0.7, height=44, width=280)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#3084F2")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Calibri} -size 18 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Solve''', command=self.solveMatrix)

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.512, rely=0.696, height=44, width=259)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#3084F2")
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Calibri} -size 18 -weight bold")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Reset''', command=self.doRefresh)

        self.Label_Equation1 = ttk.Label(self.top)
        self.Label_Equation1.place(relx=0.046, rely=0.205, height=24, width=87)
        self.Label_Equation1.configure(background="#7EB0F2")
        self.Label_Equation1.configure(foreground="#000000")
        self.Label_Equation1.configure(font="-family {Calibri} -size 12 -weight bold")
        self.Label_Equation1.configure(relief="flat")
        self.Label_Equation1.configure(anchor='w')
        self.Label_Equation1.configure(justify='left')
        self.Label_Equation1.configure(text='''Equation 1 :''')
        self.Label_Equation1.configure(compound='left')

        self.Entry1 = ttk.Entry(self.top)
        self.Entry1.place(relx=0.064, rely=0.254, relheight=0.061
                , relwidth=0.165)
        self.Entry1.configure(takefocus="")
        self.Entry1.configure(cursor="fleur")

        self.Entry2 = ttk.Entry(self.top)
        self.Entry2.place(relx=0.297, rely=0.254, relheight=0.061
                , relwidth=0.165)
        self.Entry2.configure(takefocus="")
        self.Entry2.configure(cursor="ibeam")

        self.Entry3 = ttk.Entry(self.top)
        self.Entry3.place(relx=0.528, rely=0.254, relheight=0.061
                , relwidth=0.165)
        self.Entry3.configure(takefocus="")
        self.Entry3.configure(cursor="ibeam")

        self.Entry4 = ttk.Entry(self.top)
        self.Entry4.place(relx=0.776, rely=0.254, relheight=0.061
                , relwidth=0.165)
        self.Entry4.configure(takefocus="")
        self.Entry4.configure(cursor="ibeam")

        self.TLabelX1 = ttk.Label(self.top)
        self.TLabelX1.place(relx=0.231, rely=0.254, height=33, width=37)
        self.TLabelX1.configure(background="#7EB0F2")
        self.TLabelX1.configure(foreground="#000000")
        self.TLabelX1.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelX1.configure(relief="flat")
        self.TLabelX1.configure(anchor='w')
        self.TLabelX1.configure(justify='left')
        self.TLabelX1.configure(text='''X +''')
        self.TLabelX1.configure(compound='left')

        self.Entry5 = ttk.Entry(self.top)
        self.Entry5.place(relx=0.061, rely=0.408, relheight=0.06, relwidth=0.165)

        self.Entry5.configure(takefocus="")
        self.Entry5.configure(cursor="ibeam")

        self.Entry6 = ttk.Entry(self.top)
        self.Entry6.place(relx=0.297, rely=0.408, relheight=0.06, relwidth=0.165)

        self.Entry6.configure(takefocus="")
        self.Entry6.configure(cursor="ibeam")

        self.Entry7 = ttk.Entry(self.top)
        self.Entry7.place(relx=0.528, rely=0.408, relheight=0.06, relwidth=0.165)

        self.Entry7.configure(takefocus="")
        self.Entry7.configure(cursor="ibeam")

        self.Entry8 = ttk.Entry(self.top)
        self.Entry8.place(relx=0.776, rely=0.408, relheight=0.06, relwidth=0.165)

        self.Entry8.configure(takefocus="")
        self.Entry8.configure(cursor="ibeam")

        self.Entry9 = ttk.Entry(self.top)
        self.Entry9.place(relx=0.061, rely=0.561, relheight=0.06, relwidth=0.165)

        self.Entry9.configure(takefocus="")
        self.Entry9.configure(cursor="ibeam")

        self.Entry10 = ttk.Entry(self.top)
        self.Entry10.place(relx=0.297, rely=0.561, relheight=0.06
                , relwidth=0.165)
        self.Entry10.configure(takefocus="")
        self.Entry10.configure(cursor="ibeam")

        self.Entry11 = ttk.Entry(self.top)
        self.Entry11.place(relx=0.528, rely=0.561, relheight=0.06
                , relwidth=0.165)
        self.Entry11.configure(takefocus="")
        self.Entry11.configure(cursor="ibeam")

        self.Entry12 = ttk.Entry(self.top)
        self.Entry12.place(relx=0.776, rely=0.561, relheight=0.06
                , relwidth=0.165)
        self.Entry12.configure(takefocus="")
        self.Entry12.configure(cursor="ibeam")

        self.Entry15 = ttk.Entry(self.top)
        self.Entry15.place(relx=0.759, rely=0.853, relheight=0.06
                , relwidth=0.165)
        self.Entry15.configure(takefocus="")
        self.Entry15.configure(cursor="ibeam")

        self.Entry14 = ttk.Entry(self.top)
        self.Entry14.place(relx=0.528, rely=0.853, relheight=0.06
                , relwidth=0.165)
        self.Entry14.configure(takefocus="")
        self.Entry14.configure(cursor="ibeam")

        self.Entry13 = ttk.Entry(self.top)
        self.Entry13.place(relx=0.297, rely=0.853, relheight=0.06
                , relwidth=0.165)
        self.Entry13.configure(takefocus="")
        self.Entry13.configure(cursor="fleur")

        self.TLabel_results = ttk.Label(self.top)
        self.TLabel_results.place(relx=0.066, rely=0.836, height=52, width=83)
        self.TLabel_results.configure(background="#7EB0F2")
        self.TLabel_results.configure(foreground="#000000")
        self.TLabel_results.configure(font="-family {Calibri} -size 14 -weight bold")
        self.TLabel_results.configure(relief="flat")
        self.TLabel_results.configure(anchor='w')
        self.TLabel_results.configure(justify='left')
        self.TLabel_results.configure(text='''Results :''')
        self.TLabel_results.configure(compound='left')

        self.App_title = tk.Label(self.top)
        self.App_title.place(relx=0.0, rely=0.0, height=101, width=609)
        self.App_title.configure(anchor='w')
        self.App_title.configure(background="#0455BF")
        self.App_title.configure(disabledforeground="#a3a3a3")
        self.App_title.configure(font="-family {Calibri} -size 22 -weight bold -slant italic")
        self.App_title.configure(foreground="#000000")
        self.App_title.configure(padx="10")
        self.App_title.configure(text='''Solving a 3X3 system of linear equations by ZMB''')

        self.Label_Equation2 = ttk.Label(self.top)
        self.Label_Equation2.place(relx=0.046, rely=0.34, height=24, width=87)
        self.Label_Equation2.configure(background="#7EB0F2")
        self.Label_Equation2.configure(foreground="#000000")
        self.Label_Equation2.configure(font="-family {Calibri} -size 12 -weight bold")
        self.Label_Equation2.configure(relief="flat")
        self.Label_Equation2.configure(anchor='w')
        self.Label_Equation2.configure(justify='left')
        self.Label_Equation2.configure(text='''Equation 2 :''')
        self.Label_Equation2.configure(compound='left')

        self.Label_Equation3 = ttk.Label(self.top)
        self.Label_Equation3.place(relx=0.046, rely=0.493, height=24, width=87)
        self.Label_Equation3.configure(background="#7EB0F2")
        self.Label_Equation3.configure(foreground="#000000")
        self.Label_Equation3.configure(font="-family {Calibri} -size 12 -weight bold")
        self.Label_Equation3.configure(relief="flat")
        self.Label_Equation3.configure(anchor='w')
        self.Label_Equation3.configure(justify='left')
        self.Label_Equation3.configure(text='''Equation 3 :''')
        self.Label_Equation3.configure(compound='left')

        self.TLabelX2 = ttk.Label(self.top)
        self.TLabelX2.place(relx=0.231, rely=0.408, height=33, width=36)
        self.TLabelX2.configure(background="#7EB0F2")
        self.TLabelX2.configure(foreground="#000000")
        self.TLabelX2.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelX2.configure(relief="flat")
        self.TLabelX2.configure(anchor='w')
        self.TLabelX2.configure(justify='left')
        self.TLabelX2.configure(text='''X +''')
        self.TLabelX2.configure(compound='left')

        self.TLabelY1 = ttk.Label(self.top)
        self.TLabelY1.place(relx=0.462, rely=0.254, height=33, width=36)
        self.TLabelY1.configure(background="#7EB0F2")
        self.TLabelY1.configure(foreground="#000000")
        self.TLabelY1.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelY1.configure(relief="flat")
        self.TLabelY1.configure(anchor='w')
        self.TLabelY1.configure(justify='left')
        self.TLabelY1.configure(text='''Y +''')
        self.TLabelY1.configure(compound='left')

        self.TLabelZ1 = ttk.Label(self.top)
        self.TLabelZ1.place(relx=0.693, rely=0.254, height=33, width=36)
        self.TLabelZ1.configure(background="#7EB0F2")
        self.TLabelZ1.configure(foreground="#000000")
        self.TLabelZ1.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelZ1.configure(relief="flat")
        self.TLabelZ1.configure(anchor='w')
        self.TLabelZ1.configure(justify='left')
        self.TLabelZ1.configure(text='''Z  =''')
        self.TLabelZ1.configure(compound='left')

        self.TLabelX3 = ttk.Label(self.top)
        self.TLabelX3.place(relx=0.231, rely=0.563, height=33, width=36)
        self.TLabelX3.configure(background="#7EB0F2")
        self.TLabelX3.configure(foreground="#000000")
        self.TLabelX3.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelX3.configure(relief="flat")
        self.TLabelX3.configure(anchor='w')
        self.TLabelX3.configure(justify='left')
        self.TLabelX3.configure(text='''X +''')
        self.TLabelX3.configure(compound='left')

        self.TLabelX4 = ttk.Label(self.top)
        self.TLabelX4.place(relx=0.231, rely=0.853, height=33, width=36)
        self.TLabelX4.configure(background="#7EB0F2")
        self.TLabelX4.configure(foreground="#000000")
        self.TLabelX4.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelX4.configure(relief="flat")
        self.TLabelX4.configure(anchor='w')
        self.TLabelX4.configure(justify='left')
        self.TLabelX4.configure(text='''X =''')
        self.TLabelX4.configure(compound='left')

        self.TLabelY2 = ttk.Label(self.top)
        self.TLabelY2.place(relx=0.462, rely=0.408, height=33, width=36)
        self.TLabelY2.configure(background="#7EB0F2")
        self.TLabelY2.configure(foreground="#000000")
        self.TLabelY2.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelY2.configure(relief="flat")
        self.TLabelY2.configure(anchor='w')
        self.TLabelY2.configure(justify='left')
        self.TLabelY2.configure(text='''Y +''')
        self.TLabelY2.configure(compound='left')

        self.TLabelY3 = ttk.Label(self.top)
        self.TLabelY3.place(relx=0.462, rely=0.563, height=33, width=36)
        self.TLabelY3.configure(background="#7EB0F2")
        self.TLabelY3.configure(foreground="#000000")
        self.TLabelY3.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelY3.configure(relief="flat")
        self.TLabelY3.configure(anchor='w')
        self.TLabelY3.configure(justify='left')
        self.TLabelY3.configure(text='''Y +''')
        self.TLabelY3.configure(compound='left')

        self.TLabelY4 = ttk.Label(self.top)
        self.TLabelY4.place(relx=0.462, rely=0.853, height=33, width=36)
        self.TLabelY4.configure(background="#7EB0F2")
        self.TLabelY4.configure(foreground="#000000")
        self.TLabelY4.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelY4.configure(relief="flat")
        self.TLabelY4.configure(anchor='w')
        self.TLabelY4.configure(justify='left')
        self.TLabelY4.configure(text='''Y =''')
        self.TLabelY4.configure(compound='left')

        self.TLabelZ2 = ttk.Label(self.top)
        self.TLabelZ2.place(relx=0.693, rely=0.408, height=33, width=36)
        self.TLabelZ2.configure(background="#7EB0F2")
        self.TLabelZ2.configure(foreground="#000000")
        self.TLabelZ2.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelZ2.configure(relief="flat")
        self.TLabelZ2.configure(anchor='w')
        self.TLabelZ2.configure(justify='left')
        self.TLabelZ2.configure(text='''Z  =''')
        self.TLabelZ2.configure(compound='left')

        self.TLabelZ3 = ttk.Label(self.top)
        self.TLabelZ3.place(relx=0.693, rely=0.561, height=33, width=36)
        self.TLabelZ3.configure(background="#7EB0F2")
        self.TLabelZ3.configure(foreground="#000000")
        self.TLabelZ3.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelZ3.configure(relief="flat")
        self.TLabelZ3.configure(anchor='w')
        self.TLabelZ3.configure(justify='left')
        self.TLabelZ3.configure(text='''Z  =''')
        self.TLabelZ3.configure(compound='left')

        self.TLabelZ4 = ttk.Label(self.top)
        self.TLabelZ4.place(relx=0.693, rely=0.853, height=33, width=36)
        self.TLabelZ4.configure(background="#7EB0F2")
        self.TLabelZ4.configure(foreground="#000000")
        self.TLabelZ4.configure(font="-family {Calibri} -size 16 -weight bold")
        self.TLabelZ4.configure(relief="flat")
        self.TLabelZ4.configure(anchor='w')
        self.TLabelZ4.configure(justify='left')
        self.TLabelZ4.configure(text='''Z =''')
        self.TLabelZ4.configure(compound='left')

def start_up():
    Linear_Solver_System_support.main()

if __name__ == '__main__':
    Linear_Solver_System_support.main()
